config:
  deploy_statistic_server: False
  persistent_logs: True
  store_pcaps:
    - "670"
    - "1675"
    - "mitm"
    #- "629"
    - "661"
  globals:
    coord_config:
      export_enable: True
      export_root: "powergrid-export/simbench"
      export_interval: 2
      export_name: "real_time"
    do_general_interrogation: True
    do_clock_sync: False
  sysctl:
    #"net.ipv4.tcp_syncookies": 0
    "net.ipv4.tcp_max_syn_backlog": 65535
