nodes:
  profiles:
    deploy:
      class: ProfileLoaderDeployment
      config:
        coordinator_ip: '!coord_ip'
        interpolate: cubic
        interval: 5
        ip: '!ip'
        nodeid: '!nodeid'
        powernet: '!raw_powernet'
        profile_dir: 1-MV-semiurb--0-sw
        profile_path: '!scenario_path'
        start_datetime: "2021-12-22 05:48:00"
        speed: 6
        profiles:
          load: simbench
          sgen: simbench
      module: wattson.powergrid.profiles.deployment
      type: python
    id: profiles
    interfaces: []
    name: Profile Loader
    type: host
