config:
  #switch: "mininet.node.OVSSwitch"
  #link: "mininet.link.Link"
  deploy_statistic_server: True
  globals:
    periodic_update_ms: 10000
    rtu_logic:
      "*":
        - { "class": "wattson.hosts.rtu.logic.spontaneous_logic.SpontaneousLogic" }
    coord_config:
      export_enable: True
      export_root: "powergrid-export/cigre_mv"
      grid_config: "config/trafo_config.py"
      coord_logic_scripts:
        - file: "config/coord_cosphi.py"
          class: "CoordCosPhi"
      pre_sim_noise:
        p_mw:
          sgen: "0.05kw"
          storage: "0.05kw"
        q_mvar:
          sgen: "0.1%"
      measurement_noise: False
